---
sudo: false
language: ruby
cache: bundler
bundler_args: --without system_tests development
before_install: rm Gemfile.lock || true
script:
  - 'bundle exec rake $CHECK'
matrix:
  fast_finish: true
  include:
  - rvm: 2.4
    env: PUPPET_VERSION="~> 5.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.5
    env: PUPPET_VERSION="~> 6.0" STRICT_VARIABLES="yes" CHECK=test
  - rvm: 2.5
    env: PUPPET_VERSION="~> 6.0" STRICT_VARIABLES="yes" CHECK=rubocop
  - rvm: 2.5
    env: PUPPET_INSTALL_TYPE=agent BEAKER_set=centos-7.5
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.4
    env: PUPPET_INSTALL_TYPE=agent BEAKER_set=centos-7.5
    script: bundle exec rake beaker
    services: docker
    sudo: required
  - rvm: 2.5
    env: PUPPET_INSTALL_TYPE=agent BEAKER_set=centos-7.5
    script: bundle exec rake beaker
    services: docker
    sudo: required
notifications:
  email: false
